name: nobetci
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.6
  tflite_flutter: ^0.10.4
  tflite_flutter_helper_plus: any
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.1
  vibration: ^1.9.0
  path_provider: ^2.0.11 # tflite_flutter_helper için gerekli olabilir
  image: ^3.3.0 # Görüntü işleme için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/